# FROM tiangolo/uwsgi-nginx-flask:python3.8
# RUN apk --update add bash nano
# ENV STATIC_URL /results
# ENV STATIC_PATH /var/www/app/results
# COPY ./requirements.txt /var/www/requirements.txt
# RUN pip install -r /var/www/requirements.txt
FROM tiangolo/uwsgi-nginx-flask:python3.8

COPY . /app